/** @type {import('next').NextConfig} */
const nextConfig = {
  compress: true,
  poweredByHeader: false,
  transpilePackages: [
    // react-markdown v10+ and the full unified/remark ESM-only ecosystem
    "react-markdown",
    "remark-gfm",
    "remark-parse",
    "remark-rehype",
    "unified",
    "bail",
    "is-plain-obj",
    "trough",
    "vfile",
    "vfile-message",
    "unist-util-stringify-position",
    "mdast-util-from-markdown",
    "mdast-util-to-string",
    "mdast-util-to-hast",
    "mdast-util-gfm",
    "mdast-util-gfm-autolink-literal",
    "mdast-util-gfm-footnote",
    "mdast-util-gfm-strikethrough",
    "mdast-util-gfm-table",
    "mdast-util-gfm-task-list-item",
    "mdast-util-definitions",
    "micromark",
    "micromark-core-commonmark",
    "micromark-extension-gfm",
    "micromark-extension-gfm-autolink-literal",
    "micromark-extension-gfm-footnote",
    "micromark-extension-gfm-strikethrough",
    "micromark-extension-gfm-table",
    "micromark-extension-gfm-tagfilter",
    "micromark-extension-gfm-task-list-item",
    "micromark-factory-destination",
    "micromark-factory-label",
    "micromark-factory-space",
    "micromark-factory-title",
    "micromark-factory-whitespace",
    "micromark-util-character",
    "micromark-util-chunked",
    "micromark-util-classify-character",
    "micromark-util-combine-extensions",
    "micromark-util-decode-numeric-character-reference",
    "micromark-util-decode-string",
    "micromark-util-encode",
    "micromark-util-html-tag-name",
    "micromark-util-normalize-identifier",
    "micromark-util-resolve-all",
    "micromark-util-sanitize-uri",
    "micromark-util-subtokenize",
    "micromark-util-symbol",
    "micromark-util-types",
    "unist-builder",
    "unist-util-generated",
    "unist-util-position",
    "unist-util-remove-position",
    "unist-util-visit",
    "unist-util-visit-parents",
    "unist-util-is",
    "hast-util-to-html",
    "hast-util-raw",
    "hastscript",
    "property-information",
    "space-separated-tokens",
    "comma-separated-tokens",
    "stringify-entities",
    "character-entities-html4",
    "character-entities-legacy",
    "ccount",
    "hast-util-to-jsx-runtime",
    "hast-util-whitespace",
    "hast-util-is-element",
    "html-url-attributes",
    "zwitch",
    "estree-util-is-identifier-name",
    "devlop",
  ],
  experimental: {
    serverComponentsExternalPackages: ["pdf-parse", "pg", "inngest"],
  },
  async headers() {
    return [
      {
        source: "/:path*\\.(js|css|woff|woff2|ttf|otf|ico|png|jpg|jpeg|svg|webp)",
        headers: [
          {
            key: "Cache-Control",
            value: "public, max-age=31536000, immutable",
          },
        ],
      },
      {
        source: "/api/:path*",
        headers: [
          {
            key: "Cache-Control",
            value: "no-store",
          },
        ],
      },
    ];
  },
};

export default nextConfig;
